kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: s4uMtA/LKCyYVhOqTgxc51K2VJI8dmhE32yAggM7pdc=
      - identity: {}
